with

memlist as (
    select * from {{ ref('coverage_member_list_base')}}
),

memlistrepl as (
    select * from {{ ref('coverage_mem_list_repl_base')}}
),

cvg as (
    select * from {{ ref('coverage_base')}}
)

/*copyright (c) 2017 epic systems corporation
********************************************************************************
title:   coverage_mem_list
purpose: creates a view off of coverage_member_list and coverage_mem_list_repl. this view guarantees a single row per coverage, per member for managed care coverages.
author:  jeremy albert
revision history: 
*jla 02/17 dlg#464694 - created
*cab 12/17 dlg#522044 - add mem_medicare_num_coverage and mem_legacy_hicn_coverage
*sam 04/18 dlg#541029 - remove unneeded mins for grouped columns
********************************************************************************
*/
select
    memlist.coverage_id,
    memlist.line,
    memlist.pat_id,
    memlist.mem_eff_from_date,
    memlist.mem_eff_to_date,
    memlist.mem_covered_yn,
    memlist.mem_edi_update_dt,
    memlist.mem_rel_to_sub_c,
    memlist.mem_term_reason_c,
    memlist.mem_number,
    memlist.mem_app_date,
    memlist.mem_student_yn,
    memlist.mem_late_enroll_yn,
    memlist.mem_medicare_num,
    null mem_cvg_attr,
    null ot_attr_eff_date,
    null ot_attr_term_date,
    null ot_attr_comment,
    memlist.mem_rel_to_guar_c,
    memlist.cm_phy_owner_id,
    memlist.cm_log_owner_id,
    memlist.dependent_type_c,
    memlist.court_decree_c,
    memlist.custody_c,
    memlist.mem_enroll_rsn_c,
    memlist.member_verf_user_id,
    memlist.mem_payor_name,
    memlist.mem_person_code,
    memlist.eligibility_clar_c,
    memlist.mem_verification_id,
    memlist.mem_verif_stat_c,
    memlist.last_verif_date,
    memlist.mem_sched_discon_dt,
    memlist.carrier_identifier,
    memlist.claim_identifier,
    memlist.facility_identifier,
    memlist.home_plan,
    memlist.plan_identifier,
    memlist.member_id_from_file,
    memlist.pcn_override,
    memlist.rx_billing_info_id,
    memlist.mem_mail_addr_ln_1,
    memlist.mem_mail_addr_ln_2,
    memlist.mem_mail_state_c,
    memlist.mem_mail_zip,
    memlist.mem_mail_county_c,
    memlist.mem_mail_country_c,
    memlist.mem_mail_city,
    memlist.mem_custo_name,
    memlist.mem_custo_ssn,
    memlist.mem_custo_addr_ln_1,
    memlist.mem_custo_addr_ln_2,
    memlist.mem_custo_city,
    memlist.mem_custo_state_c,
    memlist.mem_custo_zip,
    memlist.mem_custo_county_c,
    memlist.mem_custo_country_c,
    memlist.mem_custo_email,
    memlist.mem_app_time,
    memlist.hix_app_id,
    memlist.hix_origin,
    memlist.apclm_mem_ver_date,
    memlist.hix_en_addl_maint_rsn_c,
    memlist.mem_medicare_num_coverage,
    memlist.mem_legacy_hicn_coverage
  from memlist
    inner join cvg
      on memlist.coverage_id = cvg.coverage_id
    where cvg.coverage_type_c = 1
union all
select
    memlistrepl.coverage_id,
    memlistrepl.line,
    memlistrepl.pat_id,
    memlistrepl.mem_eff_from_date,
    memlistrepl.mem_eff_to_date,
    memlistrepl.mem_covered_yn,
    memlistrepl.mem_edi_update_dt,
    memlistrepl.mem_rel_to_sub_c,
    memlistrepl.mem_term_reason_c,
    memlistrepl.mem_number,
    memlistrepl.mem_app_date,
    memlistrepl.mem_student_yn,
    memlistrepl.mem_late_enroll_yn,
    memlistrepl.mem_medicare_num,
    null mem_cvg_attr,
    memlistrepl.ot_attr_eff_date,
    memlistrepl.ot_attr_term_date,
    memlistrepl.ot_attr_comment,
    memlistrepl.mem_rel_to_guar_c,
    memlistrepl.cm_phy_owner_id,
    memlistrepl.cm_log_owner_id,
    memlistrepl.dependent_type_c,
    memlistrepl.court_decree_c,
    memlistrepl.custody_c,
    memlistrepl.mem_enroll_rsn_c,
    memlistrepl.member_verf_user_id,
    memlistrepl.mem_payor_name,
    memlistrepl.mem_person_code,
    memlistrepl.eligibility_clar_c,
    memlistrepl.mem_verification_id,
    memlistrepl.mem_verif_stat_c,
    memlistrepl.last_verif_date,
    memlistrepl.mem_sched_discon_dt,
    memlistrepl.carrier_identifier,
    memlistrepl.claim_identifier,
    memlistrepl.facility_identifier,
    memlistrepl.home_plan,
    memlistrepl.plan_identifier,
    memlistrepl.member_id_from_file,
    memlistrepl.pcn_override,
    memlistrepl.rx_billing_info_id,
    memlistrepl.mem_mail_addr_ln_1,
    memlistrepl.mem_mail_addr_ln_2,
    memlistrepl.mem_mail_state_c,
    memlistrepl.mem_mail_zip,
    memlistrepl.mem_mail_county_c,
    memlistrepl.mem_mail_country_c,
    memlistrepl.mem_mail_city,
    memlistrepl.mem_custo_name,
    memlistrepl.mem_custo_ssn,
    memlistrepl.mem_custo_addr_ln_1,
    memlistrepl.mem_custo_addr_ln_2,
    memlistrepl.mem_custo_city,
    memlistrepl.mem_custo_state_c,
    memlistrepl.mem_custo_zip,
    memlistrepl.mem_custo_county_c,
    memlistrepl.mem_custo_country_c,
    memlistrepl.mem_custo_email,
    memlistrepl.mem_app_time,
    memlistrepl.hix_app_id,
    memlistrepl.hix_origin,
    memlistrepl.apclm_mem_ver_date,
    memlistrepl.hix_en_addl_maint_rsn_c,
    memlistrepl.mem_medicare_num_coverage,
    memlistrepl.mem_legacy_hicn_coverage
  from memlistrepl
    inner join cvg
      on memlistrepl.coverage_id = cvg.coverage_id
    where cvg.coverage_type_c = 1
      and not exists (  select 1
                          from memlist
                          where memlistrepl.coverage_id = memlist.coverage_id )                       
union all
select
    memlist.coverage_id,
    min(memlist.line),
    memlist.pat_id,
    null mem_eff_from_date,
    null mem_eff_to_date,
    min(memlist.mem_covered_yn),
    min(memlist.mem_edi_update_dt),
    min(memlist.mem_rel_to_sub_c),
    null mem_term_reason_c,
    min(memlist.mem_number),
    min(memlist.mem_app_date),
    min(memlist.mem_student_yn),
    min(memlist.mem_late_enroll_yn),
    min(memlist.mem_medicare_num),
    null mem_cvg_attr,
    null ot_attr_eff_date,
    null ot_attr_term_date,
    null ot_attr_comment,
    min(memlist.mem_rel_to_guar_c),
    min(memlist.cm_phy_owner_id),
    min(memlist.cm_log_owner_id),
    min(memlist.dependent_type_c),
    min(memlist.court_decree_c),
    min(memlist.custody_c),
    null mem_enroll_rsn_c,
    null member_verf_user_id,
    min(memlist.mem_payor_name),
    min(memlist.mem_person_code),
    min(memlist.eligibility_clar_c),
    null mem_verification_id,
    null mem_verif_stat_c,
    null last_verif_date,
    min(memlist.mem_sched_discon_dt),
    min(memlist.carrier_identifier),
    min(memlist.claim_identifier),
    min(memlist.facility_identifier),
    min(memlist.home_plan),
    min(memlist.plan_identifier),
    min(memlist.member_id_from_file),
    min(memlist.pcn_override),
    min(memlist.rx_billing_info_id),
    min(memlist.mem_mail_addr_ln_1),
    min(memlist.mem_mail_addr_ln_2),
    min(memlist.mem_mail_state_c),
    min(memlist.mem_mail_zip),
    min(memlist.mem_mail_county_c),
    min(memlist.mem_mail_country_c),
    min(memlist.mem_mail_city),
    min(memlist.mem_custo_name),
    min(memlist.mem_custo_ssn),
    min(memlist.mem_custo_addr_ln_1),
    min(memlist.mem_custo_addr_ln_2),
    min(memlist.mem_custo_city),
    min(memlist.mem_custo_state_c),
    min(memlist.mem_custo_zip),
    min(memlist.mem_custo_county_c),
    min(memlist.mem_custo_country_c),
    min(memlist.mem_custo_email),
    min(memlist.mem_app_time),
    min(memlist.hix_app_id),
    min(memlist.hix_origin),
    null apclm_mem_ver_date,
    min(memlist.hix_en_addl_maint_rsn_c),
    min(memlist.mem_medicare_num_coverage),
    min(memlist.mem_legacy_hicn_coverage)
  from memlist
    inner join cvg
      on memlist.coverage_id = cvg.coverage_id
    where cvg.coverage_type_c = 2
    group by memlist.coverage_id, memlist.pat_id
union all
select
    memlistrepl.coverage_id,
    min(memlistrepl.line),
    memlistrepl.pat_id,
    null mem_eff_from_date,
    null mem_eff_to_date,
    min(memlistrepl.mem_covered_yn),
    min(memlistrepl.mem_edi_update_dt),
    min(memlistrepl.mem_rel_to_sub_c),
    null mem_term_reason_c,
    min(memlistrepl.mem_number),
    min(memlistrepl.mem_app_date),
    min(memlistrepl.mem_student_yn),
    min(memlistrepl.mem_late_enroll_yn),
    min(memlistrepl.mem_medicare_num),
    null mem_cvg_attr,
    min(memlistrepl.ot_attr_eff_date),
    min(memlistrepl.ot_attr_term_date),
    min(memlistrepl.ot_attr_comment),
    min(memlistrepl.mem_rel_to_guar_c),
    min(memlistrepl.cm_phy_owner_id),
    min(memlistrepl.cm_log_owner_id),
    min(memlistrepl.dependent_type_c),
    min(memlistrepl.court_decree_c),
    min(memlistrepl.custody_c),
    null mem_enroll_rsn_c,
    null member_verf_user_id,
    min(memlistrepl.mem_payor_name),
    min(memlistrepl.mem_person_code),
    min(memlistrepl.eligibility_clar_c),
    null mem_verification_id,
    null mem_verif_stat_c,
    null last_verif_date,
    min(memlistrepl.mem_sched_discon_dt),
    min(memlistrepl.carrier_identifier),
    min(memlistrepl.claim_identifier),
    min(memlistrepl.facility_identifier),
    min(memlistrepl.home_plan),
    min(memlistrepl.plan_identifier),
    min(memlistrepl.member_id_from_file),
    min(memlistrepl.pcn_override),
    min(memlistrepl.rx_billing_info_id),
    min(memlistrepl.mem_mail_addr_ln_1),
    min(memlistrepl.mem_mail_addr_ln_2),
    min(memlistrepl.mem_mail_state_c),
    min(memlistrepl.mem_mail_zip),
    min(memlistrepl.mem_mail_county_c),
    min(memlistrepl.mem_mail_country_c),
    min(memlistrepl.mem_mail_city),
    min(memlistrepl.mem_custo_name),
    min(memlistrepl.mem_custo_ssn),
    min(memlistrepl.mem_custo_addr_ln_1),
    min(memlistrepl.mem_custo_addr_ln_2),
    min(memlistrepl.mem_custo_city),
    min(memlistrepl.mem_custo_state_c),
    min(memlistrepl.mem_custo_zip),
    min(memlistrepl.mem_custo_county_c),
    min(memlistrepl.mem_custo_country_c),
    min(memlistrepl.mem_custo_email),
    min(memlistrepl.mem_app_time),
    min(memlistrepl.hix_app_id),
    min(memlistrepl.hix_origin),
    null apclm_mem_ver_date,
    min(memlistrepl.hix_en_addl_maint_rsn_c),
    min(memlistrepl.mem_medicare_num_coverage),
    min(memlistrepl.mem_legacy_hicn_coverage)
  from memlistrepl
    inner join cvg
      on memlistrepl.coverage_id = cvg.coverage_id
    where cvg.coverage_type_c = 2
      and not exists (  select 1
                          from memlist
                          where memlistrepl.coverage_id = memlist.coverage_id )
    group by memlistrepl.coverage_id, memlistrepl.pat_id